// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v5.27.3
// source: auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export interface Empty {
}

export interface GetInforUserByIdRequest {
  userId: string;
}

export interface GetInforUserByEmailRequest {
  email: string;
}

export interface GetInforUserResponse {
  firstName: string;
  lastName: string;
  email: string;
}

export interface AuthServiceClient {
  getInforById(request: GetInforUserByIdRequest): Observable<GetInforUserResponse>;

  getInforByEmail(request: GetInforUserByEmailRequest): Observable<GetInforUserResponse>;
}

export interface AuthServiceController {
  getInforById(
    request: GetInforUserByIdRequest,
  ): Promise<GetInforUserResponse> | Observable<GetInforUserResponse> | GetInforUserResponse;

  getInforByEmail(
    request: GetInforUserByEmailRequest,
  ): Promise<GetInforUserResponse> | Observable<GetInforUserResponse> | GetInforUserResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getInforById", "getInforByEmail"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
